#!/bin/sh -e
usage() {
    echo 'usage: driff [USER@]HOST'
    exit 1
}

cachedir=~/.cache/drist

[ -z "$1" ] && usage

if ! [ -d files ] && ! [ -d "files-$1" ]; then
    echo 'files directory not found'
    exit 1
fi

rm -rf "$cachedir"
mkdir -p "$cachedir"

basedir=$(pwd)
for dir in files "files-$1"; do
    cd "$basedir" || exit 1
    if ! [ -d "$dir" ]; then
        continue
    fi
    cd "$dir" || exit 1

    find . -type f | while read -r file; do
        mkdir -p "$cachedir/${file%/*}"

        # if we don't have permission to read it
        # TODO: use tmpdir
        if ! scp scp://"$1"//"$file" "$cachedir/$file" 2> /dev/null; then
            ssh "$1" 'rm -rf ~/fanfdljnajfdnal
if command -v sudo > /dev/null; then
    SUDO=sudo
elif command -v doas > /dev/null; then
    SUDO=doas
else
    echo "sudo/doas not found or not working"
    exit 1
fi
rm -rf ~/fanfdljnajfdnal &&
mkdir -p ~/fanfdljnajfdnal/"'"${file%/*}"'" &&
$SUDO cp "/'"$file"'" ~/fanfdljnajfdnal/"'"$file"'" &&
$SUDO chmod 644 -R ~/fanfdljnajfdnal/"'"$file"'"' < /dev/null
            scp scp://"$1"/~/fanfdljnajfdnal/"$file" "$cachedir/$file"
        fi

        diff -u "$cachedir/$file" "$file"
    done
done

rm -rf "$cachedir"
